server:
  port: 8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/
zuul:
  prefix: /proxy #给网关路由添加前缀
  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤
  add-host-header: true #设置为true重定向是会添加host请求头
  routes: # 给服务配置路由
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**
# actuator需要做的配置
management:
  endpoints:
    web:
      exposure:
        include: 'routes' #开启查看路由的端点

