server:
  port: 8308
spring:
  application:
    name: nacos-ribbon-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.48:8848 #配置Nacos地址
management:
  endpoints:
    web:
      exposure:
        include: '*'

